USE [CecsoPlan01]
GO

/****** Object:  UserDefinedTableType [dbo].[CPLDAT008TD_001]    Script Date: 19/10/2022 03:28:41 p.m. ******/
CREATE TYPE [dbo].[CPLDAT008TD_001] AS TABLE(
	[ID] [int] NULL,
	[OP1] [varchar](10) NULL,
	[Fecha1] [smalldatetime] NULL,
	[Multiplos1] [decimal](4, 2) NULL,
	[Ancho1] [real] NULL,
	[Largo1] [real] NULL,
	[Lam1] [int] NULL,
	[Piezas1] [int] NULL,
	[OP2] [varchar](10) NULL,
	[Fecha2] [smalldatetime] NULL,
	[Multiplos2] [decimal](4, 2) NULL,
	[Ancho2] [real] NULL,
	[Largo2] [real] NULL,
	[Lam2] [int] NULL,
	[Piezas2] [int] NULL,
	[OP3] [varchar](10) NULL,
	[Fecha3] [smalldatetime] NULL,
	[Multiplos3] [decimal](4, 2) NULL,
	[Ancho3] [real] NULL,
	[Largo3] [real] NULL,
	[Lam3] [int] NULL,
	[Piezas3] [int] NULL,
	[Ancho Total] [real] NULL,
	[Ancho Papel] [real] NULL,
	[Refile] [real] NULL,
	[Metros Lineales] [int] NULL,
	[Producto1] [varchar](10) NULL,
	[Producto2] [varchar](10) NULL,
	[Producto3] [varchar](10) NULL,
	[Parcial1] [smallint] NULL,
	[Parcial2] [smallint] NULL,
	[Parcial3] [smallint] NULL,
	[Puntos] [int] NULL,
	[Resistencia] [varchar](12) NULL,
	[Flauta] [varchar](3) NULL,
	[Tranf] [bit] NULL,
	[Empate] [varchar](25) NULL,
	[Cliente1] [varchar](80) NULL,
	[Articulo1] [varchar](50) NULL,
	[Cliente2] [varchar](80) NULL,
	[Articulo2] [varchar](50) NULL,
	[Cliente3] [varchar](80) NULL,
	[Articulo3] [varchar](50) NULL,
	[Rest1] [varchar](12) NULL,
	[Rest2] [varchar](12) NULL,
	[Rest3] [varchar](12) NULL,
	[ConScore] [bit] NULL,
	[ConScore2] [bit] NULL,
	[ConScore3] [bit] NULL,
	[AnchoStd] [decimal](6, 2) NULL,
	[Seleccionado] [bit] NOT NULL DEFAULT ((0)),
	[ErrorResistencia] [bit] NOT NULL DEFAULT ((0)),
	[Pintado1] [bit] NOT NULL DEFAULT ((0)),
	[Pintado2] [bit] NOT NULL DEFAULT ((0)),
	[Pintado3] [bit] NOT NULL DEFAULT ((0))
)
GO


